/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BuyinghouseBill;
import java.sql.*;
import ConnectionProject.connection;
import java.awt.*;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeFormatterBuilder;
import javax.swing.JOptionPane;
import java.util.Date;
import javafx.util.converter.LocalDateTimeStringConverter;
import javax.swing.table.DefaultTableModel;
import com.itextpdf.text.Document;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;

public class billingPage extends javax.swing.JFrame {

     
    public int finalTotal=0;
    public billingPage() {
        initComponents();
        
        SimpleDateFormat dformat=new SimpleDateFormat("dd-MM-yyyy");
        Date date=new Date();
        bpdate.setText(dformat.format(date));
        
        DateTimeFormatter dtf=DateTimeFormatter.ofPattern("HH-mm-ss");
        LocalDateTime ldt=LocalDateTime.now();
        bptime.setText(dtf.format(ldt));
        bdname.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bpdate = new javax.swing.JTextField();
        bptime = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        bdname = new javax.swing.JTextField();
        bdphone = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        bdemail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        bdaddress = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        bpid = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        bpname = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        bprate = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        bpqnt = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        bpdesc = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        fulltotal = new javax.swing.JTextField();
        paidamount = new javax.swing.JTextField();
        returnamnt = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(80, 100));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BuyinghouseBill/invoice.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 74, 78));

        jLabel2.setFont(new java.awt.Font("Century Schoolbook", 1, 80)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Billing Page");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 580, 90));

        jLabel3.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 255, 204));
        jLabel3.setText("Date :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(787, 28, -1, -1));

        jLabel4.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 255, 204));
        jLabel4.setText("Time :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(787, 66, -1, -1));

        bpdate.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        getContentPane().add(bpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 30, 140, -1));

        bptime.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        getContentPane().add(bptime, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 60, 140, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 103, 1140, -1));

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 255, 204));
        jLabel5.setText("Buyer Details :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel6.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 255, 204));
        jLabel6.setText("Name:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 151, -1, -1));

        bdname.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        bdname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdnameActionPerformed(evt);
            }
        });
        getContentPane().add(bdname, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 150, -1));

        bdphone.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        bdphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdphoneActionPerformed(evt);
            }
        });
        getContentPane().add(bdphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 130, -1));

        jLabel7.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 255, 204));
        jLabel7.setText("Contract No:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, -1, -1));

        bdemail.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        bdemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdemailActionPerformed(evt);
            }
        });
        getContentPane().add(bdemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, 200, -1));

        jLabel8.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 255, 204));
        jLabel8.setText("Email :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, -1, -1));

        bdaddress.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        bdaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdaddressActionPerformed(evt);
            }
        });
        getContentPane().add(bdaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 150, 150, -1));

        jLabel9.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 255, 204));
        jLabel9.setText("Address :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 150, -1, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 179, 1180, 10));

        jLabel10.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 255, 204));
        jLabel10.setText("Product Id:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 243, -1, -1));

        bpid.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        bpid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpidActionPerformed(evt);
            }
        });
        getContentPane().add(bpid, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 110, -1));

        jLabel11.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 255, 204));
        jLabel11.setText("Product Name :");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, -1, 20));

        bpname.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        bpname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpnameActionPerformed(evt);
            }
        });
        getContentPane().add(bpname, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 150, -1));

        jLabel12.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 255, 204));
        jLabel12.setText("Product Rate :");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, -1, 20));

        bprate.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        bprate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bprateActionPerformed(evt);
            }
        });
        getContentPane().add(bprate, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 240, 100, -1));

        jLabel13.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 255, 204));
        jLabel13.setText("Quantity :");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 240, -1, -1));

        bpqnt.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        bpqnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpqntActionPerformed(evt);
            }
        });
        getContentPane().add(bpqnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 240, 80, -1));

        jLabel14.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 255, 204));
        jLabel14.setText("Product Details :");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 201, -1, -1));

        bpdesc.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        bpdesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpdescActionPerformed(evt);
            }
        });
        getContentPane().add(bpdesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 240, 120, -1));

        jLabel15.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 255, 204));
        jLabel15.setText("Description :");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 240, -1, -1));

        jButton1.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BuyinghouseBill/cart.png"))); // NOI18N
        jButton1.setText("Cart");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 280, -1, -1));

        jButton6.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BuyinghouseBill/Addition.png"))); // NOI18N
        jButton6.setText("Insert");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 280, -1, -1));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 1180, 10));

        jTable1.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "Description", "Rate", "Quantity", "Total"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 590, 220));

        jLabel16.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 255, 255));
        jLabel16.setText("Total :");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 380, -1, -1));

        jLabel17.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 255, 255));
        jLabel17.setText("Return Amount :");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 460, -1, -1));

        jLabel18.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Calculation Details : ");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 340, -1, -1));

        jLabel19.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(102, 255, 255));
        jLabel19.setText("Paid Amount :");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 420, -1, -1));

        jButton2.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BuyinghouseBill/save.png"))); // NOI18N
        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 380, -1, -1));

        jButton3.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BuyinghouseBill/refresh.png"))); // NOI18N
        jButton3.setText("Reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 380, -1, -1));

        jButton4.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BuyinghouseBill/print.png"))); // NOI18N
        jButton4.setText("Print");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 490, -1, -1));

        jButton5.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BuyinghouseBill/cancel button.png"))); // NOI18N
        jButton5.setText("Exit");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 490, -1, -1));

        jButton7.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BuyinghouseBill/Addition.png"))); // NOI18N
        jButton7.setText("Insert");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 140, -1, -1));

        fulltotal.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        getContentPane().add(fulltotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 380, 130, -1));

        paidamount.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        paidamount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paidamountActionPerformed(evt);
            }
        });
        getContentPane().add(paidamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 420, 130, -1));

        returnamnt.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        getContentPane().add(returnamnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 470, 130, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BuyinghouseBill/pexels-chasm-creative-5804275.png"))); // NOI18N
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 380, 270, -1));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BuyinghouseBill/background billing.png"))); // NOI18N
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //Print
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void bdnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdnameActionPerformed
        //BuyerName Search Action
        String bname=bdname.getText();
        try{
        Connection con=connection.getcon();
        Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select *from newbuyer where `BuyerName` like '"+bname+"%'");
            if(rs.next()){
            bdname.setText(rs.getString(1));
            bdphone.setText(rs.getString(2));
            bdemail.setText(rs.getString(3));
            bdaddress.setText(rs.getString(4));
            
            }
            else{
            bdphone.setText("");
            bdemail.setText("");
            bdaddress.setText("");
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_bdnameActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        int ext=JOptionPane.showConfirmDialog(this, "Do You Want Exit","Press Yes Or No",JOptionPane.YES_NO_CANCEL_OPTION);
        if(ext==0){
            setVisible(false);
            
        }
        else{
            setVisible(true);}
    }//GEN-LAST:event_jButton5ActionPerformed

    private void bdphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdphoneActionPerformed
        //Contarct Search Action
         String bphone=bdphone.getText();
        try{
        Connection con=connection.getcon();
        Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select *from newbuyer where `BuyerPhone` like '"+bphone+"%'");
            if(rs.next()){
            bdname.setText(rs.getString(1));
            bdphone.setText(rs.getString(2));
            bdemail.setText(rs.getString(3));
            bdaddress.setText(rs.getString(4));
            
            }
            else{
            bdname.setText("");
            bdemail.setText("");
            bdaddress.setText("");
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_bdphoneActionPerformed

    private void bdemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdemailActionPerformed
        // Email Search Action
          String bemail=bdemail.getText();
        try{
        Connection con=connection.getcon();
        Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select *from newbuyer where `BuyerEmail` like '"+bemail+"%'");
            if(rs.next()){
            bdname.setText(rs.getString(1));
            bdphone.setText(rs.getString(2));
            bdemail.setText(rs.getString(3));
            bdaddress.setText(rs.getString(4));
            
            }
            else{
            bdname.setText("");
            bdphone.setText("");
            bdaddress.setText("");
         
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_bdemailActionPerformed

    private void bdaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdaddressActionPerformed
        // Address Search Action
         String baddress=bdaddress.getText();
        try{
        Connection con=connection.getcon();
        Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select *from newbuyer where `BuyerAddress` like '"+baddress+"%'");
            if(rs.next()){
            bdname.setText(rs.getString(1));
            bdphone.setText(rs.getString(2));
            bdemail.setText(rs.getString(3));
            bdaddress.setText(rs.getString(4));
            
            }
            else{
            bdname.setText("");
            bdphone.setText("");
            bdemail.setText("");
         
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_bdaddressActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        //new Save Buyer
         String bn=bdname.getText();
        String bc=bdphone.getText();
        String be=bdemail.getText();
        String ba=bdaddress.getText();
        
        try{
        Connection con=connection.getcon();
        Statement st=con.createStatement();
        int save=st.executeUpdate("insert into newbuyer(`BuyerName`,`BuyerPhone`,`BuyerEmail`,`BuyerAddress`) values('"+bn+"','"+bc+"','"+be+"','"+ba+"')");
        if(save>0){
        JOptionPane.showMessageDialog(this,"Instant Product Save Sucesessfully!!!");
            setVisible(false);
           new billingPage().setVisible(true);
        }
        
        else{
             JOptionPane.showMessageDialog(this,"Data Save Unsucsessful!!!");
        }
        
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null,e);}
    }//GEN-LAST:event_jButton7ActionPerformed

    private void bpidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpidActionPerformed
        // TODO add your handling code here:
         String proid=bpid.getText();
        try{
        Connection con=connection.getcon();
        Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select *from newproduct where `ProductId` like '"+proid+"%'");
            if(rs.next()){
            bpid.setText(rs.getString(1));
            bpname.setText(rs.getString(2));
            bprate.setText(rs.getString(3));
            bpdesc.setText(rs.getString(4));
            
            }
            else{
            bpname.setText("");
            bprate.setText("");
            bpqnt.setText("");
            bpdesc.setText("");
         
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_bpidActionPerformed

    private void bpnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpnameActionPerformed
        // TODO add your handling code here:
            String proname=bpname.getText();
        try{
        Connection con=connection.getcon();
        Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select *from newproduct where `ProductName` like '"+proname+"%'");
            if(rs.next()){
            bpid.setText(rs.getString(1));
            bpname.setText(rs.getString(2));
            bprate.setText(rs.getString(3));
            bpdesc.setText(rs.getString(4));
            
            }
            else{
            bpid.setText("");
            bprate.setText("");
            bpqnt.setText("");
            bpdesc.setText("");
         
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_bpnameActionPerformed

    private void bprateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bprateActionPerformed
        // TODO add your handling code here:
          String prorate=bprate.getText();
        try{
        Connection con=connection.getcon();
        Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select *from newproduct where `ProductPrice` like '"+prorate+"%'");
            if(rs.next()){
            bpid.setText(rs.getString(1));
            bpname.setText(rs.getString(2));
            bprate.setText(rs.getString(3));
            bpdesc.setText(rs.getString(4));
            
            }
            else{
            bpid.setText("");
            bpname.setText("");
            bpqnt.setText("");
            bpdesc.setText("");
         
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_bprateActionPerformed

    private void bpqntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpqntActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_bpqntActionPerformed

    private void bpdescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpdescActionPerformed
        // TODO add your handling code here:
           String prodes=bpdesc.getText();
        try{
        Connection con=connection.getcon();
        Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select *from newproduct where `ProductDescription` like '"+prodes+"%'");
            if(rs.next()){
            bpid.setText(rs.getString(1));
            bpname.setText(rs.getString(2));
            bprate.setText(rs.getString(3));
            bpdesc.setText(rs.getString(4));
            
            }
            else{
            bpid.setText("");
            bpname.setText("");
            bprate.setText("");
            bpqnt.setText("");
            
         
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_bpdescActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        //Instant Product Save
         String pid=bpid.getText();
        String pname=bpname.getText();
        String prate=bprate.getText();
        String pdesp=bpdesc.getText();
        
           try{
           Connection con=connection.getcon();
           Statement st=con.createStatement();
           int proadd=st.executeUpdate("insert into newproduct(ProductId,ProductName,ProductPrice,ProductDescription) values('"+pid+"','"+pname+"','"+prate+"','"+pdesp+"')");
           if(proadd>0){
               JOptionPane.showMessageDialog(this, "New Product Entry Sucessfully!!");
               setVisible(false);
               new billingPage().setVisible(true);
           }
            else{
           JOptionPane.showMessageDialog(this,"Data Entry Faild!!");
           }
           }
          
           catch(Exception e){
               JOptionPane.showMessageDialog(null, e);
           }
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Cart
        if(bpqnt.getText().isEmpty()){
        JOptionPane.showMessageDialog(this,"Quantity is Empty!!");
        bpqnt.requestFocus();
        }
        else{
        int rate=Integer.parseInt(bprate.getText());
        int qnty=Integer.parseInt(bpqnt.getText());
        int total=rate*qnty;
        DefaultTableModel dtm=(DefaultTableModel)jTable1.getModel();
        dtm.addRow(new Object[]{bpname.getText(),bpdesc.getText(),bprate.getText(),bpqnt.getText(),total});
        finalTotal=finalTotal+total;
        String totaladd=String.valueOf(finalTotal);
        fulltotal.setText(totaladd);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void paidamountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paidamountActionPerformed
        //Pain Amount
        String paid=paidamount.getText();
        String stol=fulltotal.getText();
        int paidamt=Integer.parseInt(paid);
        int subtol=Integer.parseInt(stol);
        int total=subtol-paidamt;
       returnamnt.setText(""+total);
        
    }//GEN-LAST:event_paidamountActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //Reset
        setVisible(false);
        new billingPage().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //Save
        if(paidamount.getText().isEmpty()){
        JOptionPane.showMessageDialog(this,"Paid Ammount is Empty");}
        else{
        String bname=bdname.getText();
        String bphone=bdphone.getText();
        String bemail=bdemail.getText();
        String badds=bdaddress.getText();
       
        String path=("F:\\JavaNetBeansProject\\billingpdf\\");
        com.itextpdf.text.Document doc= new com.itextpdf.text.Document();
        try{
            PdfWriter.getInstance(doc, new FileOutputStream(path+""+bname+" "+bpdate.getText()+" "+bptime.getText()+".pdf"));
            doc.open();
            Paragraph para1=new Paragraph("                                 Prema Group & Company\n                              Contract No:01682682284\n");
            doc.add(para1);
            Paragraph para2=new Paragraph("Date&Time :"+bpdate.getText()+" "+bptime.getText()+"\n Buyer Details :\n Name:"+bname+"\n Contract No:"+bphone+"\n Email:"+bemail+"\n Address :"+badds+"\n\n");
            doc.add(para2);
            PdfPTable pdft=new PdfPTable(5);
            pdft.addCell("Name");
             pdft.addCell("Description");
              pdft.addCell("Rate");
               pdft.addCell("Quantity");
                pdft.addCell("Sub Total");
                for (int i = 0; i < jTable1.getRowCount();i++) {
                    String name=jTable1.getValueAt(i,0).toString();
                    String des=jTable1.getValueAt(i,1).toString();
                    String rate=jTable1.getValueAt(i,2).toString();
                    String qnt=jTable1.getValueAt(i,3).toString();
                    String stotal=jTable1.getValueAt(i,4).toString();
                    pdft.addCell(name);
                    pdft.addCell(des);
                    pdft.addCell(rate);
                    pdft.addCell(qnt);
                    pdft.addCell(stotal);
              
            }
                doc.add(pdft);
                Paragraph para3=new Paragraph("\n Total Amount:"+fulltotal.getText()+"\n Paid Amount :"+paidamount.getText()+"\n Return Amount:"+returnamnt.getText()+"\n\n       Thank You Sir!! \n Please Come Again!! ");
             doc.add(para3);
             JOptionPane.showMessageDialog(this, "Save Sucssfully!!");
             new billingPage().setVisible(true);
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, e);}
      doc.close();}
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(billingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(billingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(billingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(billingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new billingPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bdaddress;
    private javax.swing.JTextField bdemail;
    private javax.swing.JTextField bdname;
    private javax.swing.JTextField bdphone;
    private javax.swing.JTextField bpdate;
    private javax.swing.JTextField bpdesc;
    private javax.swing.JTextField bpid;
    private javax.swing.JTextField bpname;
    private javax.swing.JTextField bpqnt;
    private javax.swing.JTextField bprate;
    private javax.swing.JTextField bptime;
    private javax.swing.JTextField fulltotal;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField paidamount;
    private javax.swing.JTextField returnamnt;
    // End of variables declaration//GEN-END:variables
}
