/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BuyinghouseBill;
import java.awt.Color;
import java.sql.*;
import ConnectionProject.connection;
import javax.swing.JOptionPane;

/**
 *
 * @author akib2
 */
public class deleteBuyer extends javax.swing.JFrame {

    /**
     * Creates new form deleteBuyer
     */
    public deleteBuyer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        searchtf = new javax.swing.JTextField();
        searchbutton = new javax.swing.JButton();
        dbn = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        dbc = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        dbe = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        dbadd = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        dbgen = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(380, 160));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(0, 204, 0));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Update Name :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 210, 30));

        searchtf.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        searchtf.setForeground(new java.awt.Color(0, 102, 51));
        searchtf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchtfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchtfFocusLost(evt);
            }
        });
        searchtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchtfActionPerformed(evt);
            }
        });
        getContentPane().add(searchtf, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 100, 230, -1));

        searchbutton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        searchbutton.setForeground(new java.awt.Color(0, 0, 102));
        searchbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BuyinghouseBill/search.png"))); // NOI18N
        searchbutton.setText("Search");
        searchbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(searchbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 151, 30));

        dbn.setBackground(new java.awt.Color(0, 153, 153));
        dbn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dbn.setForeground(new java.awt.Color(0, 0, 51));
        dbn.setText("For Update Name");
        dbn.setDisabledTextColor(new java.awt.Color(255, 204, 102));
        dbn.setSelectedTextColor(new java.awt.Color(255, 51, 51));
        dbn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dbnFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                dbnFocusLost(evt);
            }
        });
        dbn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dbnKeyPressed(evt);
            }
        });
        getContentPane().add(dbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 220, 32));

        jLabel4.setBackground(new java.awt.Color(0, 204, 0));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Update Contract :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 210, 30));

        dbc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dbc.setForeground(new java.awt.Color(0, 0, 51));
        dbc.setText("For Update Contract");
        dbc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dbcFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                dbcFocusLost(evt);
            }
        });
        dbc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dbcKeyPressed(evt);
            }
        });
        getContentPane().add(dbc, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 220, 32));

        jLabel5.setBackground(new java.awt.Color(0, 204, 0));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Update Buyer Email :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 210, 34));

        dbe.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dbe.setForeground(new java.awt.Color(0, 0, 51));
        dbe.setText("For Update Email");
        dbe.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dbeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                dbeFocusLost(evt);
            }
        });
        dbe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dbeKeyPressed(evt);
            }
        });
        getContentPane().add(dbe, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 220, 32));

        jLabel6.setBackground(new java.awt.Color(0, 204, 0));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Update Buyer Address :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, 26));

        dbadd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dbadd.setForeground(new java.awt.Color(0, 0, 51));
        dbadd.setText("For Update Address");
        dbadd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dbaddFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                dbaddFocusLost(evt);
            }
        });
        dbadd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dbaddKeyPressed(evt);
            }
        });
        getContentPane().add(dbadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 220, 32));

        jLabel7.setBackground(new java.awt.Color(0, 204, 0));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Update Gender :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 210, 31));

        dbgen.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dbgen.setForeground(new java.awt.Color(0, 0, 51));
        dbgen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select One", "Male", "Female", "others" }));
        getContentPane().add(dbgen, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, 220, 30));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BuyinghouseBill/delete.png"))); // NOI18N
        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 51, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BuyinghouseBill/refresh.png"))); // NOI18N
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, -1, 30));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 102, 204));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BuyinghouseBill/close Jframe.png"))); // NOI18N
        jButton3.setText("Close");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 410, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 89, 541, 12));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 204));
        jLabel1.setText("Buyer Delete");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 353, 71));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BuyinghouseBill/delete buyer.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 74, 71));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BuyinghouseBill/pexels-snapwire-34950.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchtfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchtfFocusGained
        // focus gain Search Textfield
      
    }//GEN-LAST:event_searchtfFocusGained

    private void searchtfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchtfFocusLost
        //focus lost Search Textfield
        
    }//GEN-LAST:event_searchtfFocusLost

    private void searchbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbuttonActionPerformed
        //Search
        String search=searchtf.getText();
        try{
            Connection con=connection.getcon();
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select *from newbuyer where BuyerPhone like '"+search+"%'");
            if(rs.next()){
                dbn.setText(rs.getString(1));
                dbc.setText(rs.getString(2));
                dbe.setText(rs.getString(3));
                dbadd.setText(rs.getString(4));
                dbgen.setSelectedItem(rs.getString(5));}
            else{

                JOptionPane.showMessageDialog(this, "Not Found Here Buyer");}

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Buyer Is Not Found Here","Please Give Right Contract",JOptionPane.WARNING_MESSAGE);}

    }//GEN-LAST:event_searchbuttonActionPerformed

    private void dbnFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dbnFocusGained
        // TODO add your handling code here:
       
    }//GEN-LAST:event_dbnFocusGained

    private void dbnFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dbnFocusLost
        // TODO add your handling code here:
       
    }//GEN-LAST:event_dbnFocusLost

    private void dbnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dbnKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_dbnKeyPressed

    private void dbcFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dbcFocusGained
        // TODO add your handling code here:
       
    }//GEN-LAST:event_dbcFocusGained

    private void dbcFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dbcFocusLost
        // TODO add your handling code here:
       
    }//GEN-LAST:event_dbcFocusLost

    private void dbcKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dbcKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_dbcKeyPressed

    private void dbeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dbeFocusGained
        // TODO add your handling code here:
     
    }//GEN-LAST:event_dbeFocusGained

    private void dbeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dbeFocusLost
        // TODO add your handling code here:
     
    }//GEN-LAST:event_dbeFocusLost

    private void dbeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dbeKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_dbeKeyPressed

    private void dbaddFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dbaddFocusGained
        // TODO add your handling code here:
       
    }//GEN-LAST:event_dbaddFocusGained

    private void dbaddFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dbaddFocusLost
        // TODO add your handling code here:
      
    }//GEN-LAST:event_dbaddFocusLost

    private void dbaddKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dbaddKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_dbaddKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Delete Buyer
        int dc=JOptionPane.showConfirmDialog(this,"Do you want to delete!!","Select Any one",JOptionPane.YES_NO_CANCEL_OPTION);
    if(dc==0){
        String buyerphone=dbc.getText();
   
        try{
            Connection con=connection.getcon();
            Statement st=con.createStatement();
            int upb=st.executeUpdate("delete  from newbuyer where `BuyerPhone` ='"+buyerphone+"'");
           
            if(upb>0){
                JOptionPane.showMessageDialog(this, "Buyer Document Delete Sucesessfully!!!");
                setVisible(false);
                new deleteBuyer().setVisible(true);
            }
            else{
                JOptionPane.showMessageDialog(this, "Buyer data Not Delete");}
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }}

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new deleteBuyer().setVisible(true);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        setVisible(false);

    }//GEN-LAST:event_jButton3ActionPerformed

    private void searchtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchtfActionPerformed
        // TODO add your handling code here:
          
        
        
    }//GEN-LAST:event_searchtfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(deleteBuyer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(deleteBuyer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(deleteBuyer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(deleteBuyer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new deleteBuyer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dbadd;
    private javax.swing.JTextField dbc;
    private javax.swing.JTextField dbe;
    private javax.swing.JComboBox<String> dbgen;
    private javax.swing.JTextField dbn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton searchbutton;
    private javax.swing.JTextField searchtf;
    // End of variables declaration//GEN-END:variables
}
