/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BuyinghouseBill;

import java.sql.*;
import java.awt.Color;
import ConnectionProject.connection;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
public class deleteProduct extends javax.swing.JFrame {

    /**
     * Creates new form deleteProduct
     */
    public deleteProduct() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        prodid = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        dprodname = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        dprodrate = new javax.swing.JTextField();
        dproddes = new javax.swing.JTextField();
        activebox = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        searchbutton = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(380, 160));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 51, 51));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BuyinghouseBill/trash.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 70, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 0));
        jLabel2.setText("Delete Product");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 13, 375, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 51));
        jLabel3.setText("Product ID :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 213, 39));

        prodid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        prodid.setForeground(new java.awt.Color(102, 0, 102));
        prodid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                prodidKeyReleased(evt);
            }
        });
        getContentPane().add(prodid, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 200, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 51));
        jLabel6.setText("Product Name");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 141, 30));

        dprodname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dprodname.setForeground(new java.awt.Color(102, 0, 102));
        dprodname.setText("Enter Product Name");
        dprodname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dprodnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                dprodnameFocusLost(evt);
            }
        });
        dprodname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dprodnameActionPerformed(evt);
            }
        });
        dprodname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dprodnameKeyPressed(evt);
            }
        });
        getContentPane().add(dprodname, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 210, 30));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 132, 580, -1));

        dprodrate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dprodrate.setForeground(new java.awt.Color(102, 0, 102));
        dprodrate.setText("Enter Product Price");
        dprodrate.setPreferredSize(new java.awt.Dimension(184, 23));
        dprodrate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dprodrateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                dprodrateFocusLost(evt);
            }
        });
        dprodrate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dprodrateKeyPressed(evt);
            }
        });
        getContentPane().add(dprodrate, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 210, 30));

        dproddes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dproddes.setForeground(new java.awt.Color(102, 0, 102));
        dproddes.setText("Enter Product Description");
        dproddes.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dproddesFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                dproddesFocusLost(evt);
            }
        });
        dproddes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dproddesKeyPressed(evt);
            }
        });
        getContentPane().add(dproddes, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 210, 29));

        activebox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        activebox.setForeground(new java.awt.Color(102, 0, 102));
        activebox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select One", "Yes", "No" }));
        activebox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                activeboxKeyPressed(evt);
            }
        });
        getContentPane().add(activebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 210, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 51));
        jLabel7.setText("Rate");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 141, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 51));
        jLabel8.setText("Desciptions");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 141, 29));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 51));
        jLabel9.setText("Activate");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 141, 28));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BuyinghouseBill/delete.png"))); // NOI18N
        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BuyinghouseBill/refresh.png"))); // NOI18N
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, -1, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BuyinghouseBill/cancel button.png"))); // NOI18N
        jButton3.setText("Close");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 400, -1, -1));

        searchbutton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        searchbutton.setForeground(new java.awt.Color(0, 0, 102));
        searchbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BuyinghouseBill/search.png"))); // NOI18N
        searchbutton.setText("Search");
        searchbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(searchbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 151, 30));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 379, 580, 10));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 74, 572, 10));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BuyinghouseBill/pexels-photomix-company-96627.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void prodidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prodidKeyReleased
        // TODO add your handling code here:
        if(prodid.getText().equals("")){
        }
    }//GEN-LAST:event_prodidKeyReleased

    private void dprodnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dprodnameFocusGained
        //name focus
        if(dprodname.getText().equals("Enter Product Name")){
            dprodname.setText("");
            dprodname.setForeground(new Color(102,0,102));
        }
    }//GEN-LAST:event_dprodnameFocusGained

    private void dprodnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dprodnameFocusLost
        // TODO add your handling code here:
        if(dprodname.getText().equals("")){
            dprodname.setText("Enter Product Name");
            dprodname.setForeground(new Color(102,0,102));
        }
    }//GEN-LAST:event_dprodnameFocusLost

    private void dprodnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dprodnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dprodnameActionPerformed

    private void dprodnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dprodnameKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(dprodname.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Product Name Is Empty","Please Submit Name",JOptionPane.WARNING_MESSAGE);
            }
            else{dprodrate.requestFocus();}
        }
        else if(evt.getKeyCode()==KeyEvent.VK_DOWN){
            if(dprodname.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Product Rate Is Empty","Please Submit Name",JOptionPane.WARNING_MESSAGE);
            }
            else{dprodrate.requestFocus();}
        }
    }//GEN-LAST:event_dprodnameKeyPressed

    private void dprodrateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dprodrateFocusGained
        // TODO add your handling code here:
        if(dprodrate.getText().equals("Enter Product Price")){
            dprodrate.setText("");
            dprodrate.setForeground(new Color(102,0,102));
        }
    }//GEN-LAST:event_dprodrateFocusGained

    private void dprodrateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dprodrateFocusLost
        // TODO add your handling code here:
        if(dprodrate.getText().equals("")){
            dprodrate.setText("Enter Product Price");
            dprodrate.setForeground(new Color(102,0,102));
        }
    }//GEN-LAST:event_dprodrateFocusLost

    private void dprodrateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dprodrateKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(dprodrate.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Product Rate Is Empty","Please Submit Rate",JOptionPane.WARNING_MESSAGE);
            }
            else{dproddes.requestFocus();}
        }
        else if(evt.getKeyCode()==KeyEvent.VK_DOWN){
            if(dprodrate.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Product Rate Is Empty","Please Submit Rate",JOptionPane.WARNING_MESSAGE);
            }
            else{dproddes.requestFocus();}
        }
    }//GEN-LAST:event_dprodrateKeyPressed

    private void dproddesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dproddesFocusGained
        // TODO add your handling code here:
        if(dproddes.getText().equals("Enter Product Description")){
            dproddes.setText("");
            dproddes.setForeground(new Color(102,0,102));
        }
    }//GEN-LAST:event_dproddesFocusGained

    private void dproddesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dproddesFocusLost
        // TODO add your handling code here:
        if(dproddes.getText().equals("")){
            dproddes.setText("Enter Product Description");
            dproddes.setForeground(new Color(102,0,102));
        }
    }//GEN-LAST:event_dproddesFocusLost

    private void dproddesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dproddesKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(dproddes.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Product Rate Is Desciption","Please Submit Desciption",JOptionPane.WARNING_MESSAGE);
            }
            else{activebox.requestFocus();}
        }
        else if(evt.getKeyCode()==KeyEvent.VK_DOWN){
            if(dproddes.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Product Rate Is Desciption","Please Submit Desciption",JOptionPane.WARNING_MESSAGE);
            }
            else{activebox.requestFocus();}
        }
    }//GEN-LAST:event_dproddesKeyPressed

    private void activeboxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_activeboxKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(activebox.getSelectedIndex()==0){
                JOptionPane.showMessageDialog(this, "Product Active Is Empty","Please Submit Activation",JOptionPane.WARNING_MESSAGE);
            }
            else{dprodname.requestFocus();}
        }
        else if(evt.getKeyCode()==KeyEvent.VK_DOWN){
            if(dprodrate.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Product Active Is Empty","Please Submit Activation",JOptionPane.WARNING_MESSAGE);
            }
            else{dprodname.requestFocus();}

        }
    }//GEN-LAST:event_activeboxKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Product Save
        String pid=prodid.getText();
       int del=JOptionPane.showConfirmDialog(this, "Are You Sure Delete this Product???","Select One",JOptionPane.YES_NO_CANCEL_OPTION);
       if(del==0){
        try{
            Connection con=connection.getcon();
            Statement st=con.createStatement();
            int proadd=st.executeUpdate("delete from newproduct where `ProductId`='"+pid+"'");
            if(proadd>0){
                JOptionPane.showMessageDialog(this, "Product Delete Sucessfully!!");
                setVisible(false);
                new deleteProduct().setVisible(true);
            }
            else{
                JOptionPane.showMessageDialog(this,"Data Not Selected!!");
            }
        }

        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
       }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //refresh
        setVisible(false);
        new deleteProduct().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //close
        setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void searchbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbuttonActionPerformed
        //Search
        String search=prodid.getText();
        try{
            Connection con=connection.getcon();
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select *from newproduct where `ProductId`='"+search+"'");
            if(rs.next()){
                dprodname.setText(rs.getString(2));
                dprodrate.setText(rs.getString(3));
                dproddes.setText(rs.getString(4));
                activebox.setSelectedItem(rs.getString(5));}
            else{

                JOptionPane.showMessageDialog(this, "Not Found Here Buyer");}

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Buyer Is Not Found Here","Please Give Right Contract",JOptionPane.WARNING_MESSAGE);}
    }//GEN-LAST:event_searchbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(deleteProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(deleteProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(deleteProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(deleteProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new deleteProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> activebox;
    private javax.swing.JTextField dproddes;
    private javax.swing.JTextField dprodname;
    private javax.swing.JTextField dprodrate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField prodid;
    private javax.swing.JButton searchbutton;
    // End of variables declaration//GEN-END:variables
}
