
package BuyinghouseBill;

import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import ConnectionProject.connection;
import java.sql.*;

/**
 *
 * @author akib2
 */
public class newBuyer extends javax.swing.JFrame {

    /**
     * Creates new form newBuyer
     */
    public newBuyer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        bcn = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        bei = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        badd = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        bgen = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(380, 160));
        setMinimumSize(new java.awt.Dimension(600, 450));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Buyer Name :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 116, 129, 23));

        bname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bname.setForeground(new java.awt.Color(153, 153, 255));
        bname.setText("Enter Name");
        bname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                bnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                bnameFocusLost(evt);
            }
        });
        bname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnameActionPerformed(evt);
            }
        });
        bname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bnameKeyPressed(evt);
            }
        });
        getContentPane().add(bname, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 116, 179, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Buyer Contract :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 157, 129, 23));

        bcn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bcn.setForeground(new java.awt.Color(153, 153, 255));
        bcn.setText("Contract No");
        bcn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                bcnFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                bcnFocusLost(evt);
            }
        });
        bcn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcnActionPerformed(evt);
            }
        });
        bcn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bcnKeyPressed(evt);
            }
        });
        getContentPane().add(bcn, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 157, 179, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Email :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 198, 129, 23));

        bei.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bei.setForeground(new java.awt.Color(153, 153, 255));
        bei.setText("@example.com");
        bei.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                beiFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                beiFocusLost(evt);
            }
        });
        bei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beiActionPerformed(evt);
            }
        });
        bei.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                beiKeyPressed(evt);
            }
        });
        getContentPane().add(bei, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 198, 179, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Address :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 239, 129, 31));

        badd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        badd.setForeground(new java.awt.Color(153, 153, 255));
        badd.setText("Present address");
        badd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                baddFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                baddFocusLost(evt);
            }
        });
        badd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                baddKeyPressed(evt);
            }
        });
        getContentPane().add(badd, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 179, 31));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Gender :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 288, 129, 29));

        bgen.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bgen.setForeground(new java.awt.Color(153, 153, 255));
        bgen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other", " " }));
        bgen.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                bgenFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                bgenFocusLost(evt);
            }
        });
        bgen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bgenKeyPressed(evt);
            }
        });
        getContentPane().add(bgen, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 288, 179, 29));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BuyinghouseBill/save.png"))); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 356, -1, 41));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BuyinghouseBill/Knob-Refresh-icon.png"))); // NOI18N
        jButton2.setText("Refresh");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 356, -1, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BuyinghouseBill/cancel button.png"))); // NOI18N
        jButton3.setText("Close");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 356, -1, 41));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("New Buyer ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 420, 68));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BuyinghouseBill/new.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 90, 68));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BuyinghouseBill/managed-it-services-696x455.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bnameActionPerformed

    private void bcnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bcnActionPerformed

    private void beiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_beiActionPerformed

    private void bnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bnameFocusGained
        //buyer name foucus gain
        if(bname.getText().equals("Enter Name")){
        bname.setText("");
        bname.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_bnameFocusGained

    private void bnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bnameFocusLost
        // buyer name focus lost
         if(bname.getText().equals("")){
        bname.setText("Enter Name");
        bname.setForeground(new Color(153,153,255));
        }
    }//GEN-LAST:event_bnameFocusLost

    private void bcnFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bcnFocusGained
        //contract number gain
         if(bcn.getText().equals("Contract No")){
        bcn.setText("");
        bcn.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_bcnFocusGained

    private void bcnFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bcnFocusLost
         // buyer name focus lost
         if(bcn.getText().equals("")){
        bcn.setText("Contract No");
        bcn.setForeground(new Color(153,153,255));
        }
    }//GEN-LAST:event_bcnFocusLost

    private void beiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_beiFocusGained
        // Tbuyer email focus gain:
         if(bei.getText().equals("@example.com")){
        bei.setText("");
        bei.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_beiFocusGained

    private void beiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_beiFocusLost
         // buyer email focus lost
         if(bei.getText().equals("")){
        bei.setText("@example.com");
        bei.setForeground(new Color(153,153,255));
        }
    }//GEN-LAST:event_beiFocusLost

    private void baddFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_baddFocusGained
        //buyer address gain
         if(badd.getText().equals("Present address")){
        badd.setText("");
        badd.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_baddFocusGained

    private void baddFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_baddFocusLost
          // buyer name focus lost
         if(badd.getText().equals("")){
        badd.setText("Present address");
        badd.setForeground(new Color(153,153,255));
        }
    }//GEN-LAST:event_baddFocusLost

    private void bgenFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bgenFocusGained
        // TODO add your handling code here:
       
    }//GEN-LAST:event_bgenFocusGained

    private void bgenFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bgenFocusLost
          // buyer name focus lost
    }//GEN-LAST:event_bgenFocusLost

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //close button
        setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Refresh button
        setVisible(false);
        new newBuyer().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void bnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bnameKeyPressed
        //buyer name box enter key
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(bname.getText().isEmpty()){
       JOptionPane.showMessageDialog(this,"Buyer is Empty !!","Please Enter Name",JOptionPane.WARNING_MESSAGE);
        }else{
        bcn.requestFocus();}
        }
       
         else if(evt.getKeyCode()==KeyEvent.VK_DOWN){
            if(bname.getText().isEmpty()){
       JOptionPane.showMessageDialog(this,"Buyer is Empty !!","Please Enter Name",JOptionPane.WARNING_MESSAGE);
        }else{
        bcn.requestFocus();}
        }
    }//GEN-LAST:event_bnameKeyPressed

    private void bcnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bcnKeyPressed
        //buyer contract press
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(bcn.getText().isEmpty()){
       JOptionPane.showMessageDialog(this,"Buyer Contract is Empty !!","Please Enter Conter Number",JOptionPane.WARNING_MESSAGE);
        }else{
        bei.requestFocus();}
        }
      
         else if(evt.getKeyCode()==KeyEvent.VK_DOWN){
            if(bcn.getText().isEmpty()){
       JOptionPane.showMessageDialog(this,"Buyer Contract is Empty !!","Please Enter Conter Number",JOptionPane.WARNING_MESSAGE);
        }else{
        bei.requestFocus();}
        }
    }//GEN-LAST:event_bcnKeyPressed

    private void beiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_beiKeyPressed
        //buyer email key press
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(bei.getText().isEmpty()){
       JOptionPane.showMessageDialog(this,"Email ID Empty !!","Please Enter Email ID",JOptionPane.WARNING_MESSAGE);
        }else{
        badd.requestFocus();}
        }
        
         else if(evt.getKeyCode()==KeyEvent.VK_DOWN){
            if(bei.getText().isEmpty()){
       JOptionPane.showMessageDialog(this,"Email ID Empty !!","Please Enter Email ID",JOptionPane.WARNING_MESSAGE);
        }else{
        badd.requestFocus();}
        }
    }//GEN-LAST:event_beiKeyPressed

    private void baddKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_baddKeyPressed
        // buyer address key pressed
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(badd.getText().isEmpty()){
       JOptionPane.showMessageDialog(this,"Buyer Address is Empty !!","Please Enter Address",JOptionPane.WARNING_MESSAGE);
        }else{
        bgen.requestFocus();}
        }
        
         else if(evt.getKeyCode()==KeyEvent.VK_DOWN){
            if(badd.getText().isEmpty()){
       JOptionPane.showMessageDialog(this,"Buyer Address is Empty !!","Please Enter Address",JOptionPane.WARNING_MESSAGE);
        }else{
        bgen.requestFocus();}
        }
    }//GEN-LAST:event_baddKeyPressed

    private void bgenKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bgenKeyPressed
        // gender combobox KeyPress
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        if(bgen.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(this,"NOT Seleted Gender","Give this Info",JOptionPane.WARNING_MESSAGE);
        }else{
        bgen.requestFocus();}
        }
    }//GEN-LAST:event_bgenKeyPressed
 

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Save
        String bn=bname.getText();
        String bc=bcn.getText();
        String be=bei.getText();
        String ba=badd.getText();
        String bg=bgen.getSelectedItem().toString();
        try{
        Connection con=connection.getcon();
        Statement st=con.createStatement();
        int save=st.executeUpdate("insert into newbuyer values('"+bn+"','"+bc+"','"+be+"','"+ba+"','"+bg+"')");
        if(save>0){
        JOptionPane.showMessageDialog(this,"Data Save Sucesessfully!!!");
            setVisible(false);
            new newBuyer().setVisible(true);
        }
        
        else{
             JOptionPane.showMessageDialog(this,"Data Save Unsucsessful!!!");
        }
        
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(this,"Mobile Number Already Done!!!!");}
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newBuyer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newBuyer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newBuyer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newBuyer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newBuyer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField badd;
    private javax.swing.JTextField bcn;
    private javax.swing.JTextField bei;
    private javax.swing.JComboBox<String> bgen;
    private javax.swing.JTextField bname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
