/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BuyinghouseBill;

import java.awt.Color;
import java.sql.*;
import ConnectionProject.connection;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javafx.stage.Stage;

public class newProduct extends javax.swing.JFrame {

    /**
     * Creates new form newProduct
     */
   
  
    public newProduct() {
        initComponents();
        prodname.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        prodid = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        prodname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        prodrate = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        proddes = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        activebox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(380, 160));
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BuyinghouseBill/new.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 11, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 51));
        jLabel2.setText("New Product");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 13, 375, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 77, 580, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("Product ID :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 85, 213, 39));

        prodid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        prodid.setForeground(new java.awt.Color(102, 0, 102));
        prodid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                prodidKeyReleased(evt);
            }
        });
        getContentPane().add(prodid, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 200, 30));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 132, 580, -1));

        prodname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        prodname.setForeground(new java.awt.Color(102, 0, 102));
        prodname.setText("Enter Product Name");
        prodname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                prodnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                prodnameFocusLost(evt);
            }
        });
        prodname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodnameActionPerformed(evt);
            }
        });
        prodname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                prodnameKeyPressed(evt);
            }
        });
        getContentPane().add(prodname, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 210, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Product Name");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 141, 30));

        prodrate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        prodrate.setForeground(new java.awt.Color(102, 0, 102));
        prodrate.setText("Enter Product Price");
        prodrate.setPreferredSize(new java.awt.Dimension(184, 23));
        prodrate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                prodrateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                prodrateFocusLost(evt);
            }
        });
        prodrate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                prodrateKeyPressed(evt);
            }
        });
        getContentPane().add(prodrate, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 220, 210, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Rate");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 141, 30));

        proddes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        proddes.setForeground(new java.awt.Color(102, 0, 102));
        proddes.setText("Enter Product Description");
        proddes.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                proddesFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                proddesFocusLost(evt);
            }
        });
        proddes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                proddesKeyPressed(evt);
            }
        });
        getContentPane().add(proddes, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 210, 29));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Desciptions");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 141, 29));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Activate");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 141, 28));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BuyinghouseBill/save.png"))); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BuyinghouseBill/refresh.png"))); // NOI18N
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, -1, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BuyinghouseBill/cancel button.png"))); // NOI18N
        jButton3.setText("Close");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 400, -1, -1));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 379, 580, 10));

        activebox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        activebox.setForeground(new java.awt.Color(102, 0, 102));
        activebox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select One", "Yes", "No" }));
        activebox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                activeboxKeyPressed(evt);
            }
        });
        getContentPane().add(activebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 210, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BuyinghouseBill/pexels-omar-houchaimi-752525.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void prodnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prodnameActionPerformed

    private void prodnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_prodnameFocusGained
        //name focus
        if(prodname.getText().equals("Enter Product Name")){
        prodname.setText("");
        prodname.setForeground(new Color(102,0,102));
        }
    }//GEN-LAST:event_prodnameFocusGained

    private void prodnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_prodnameFocusLost
        // TODO add your handling code here:
          if(prodname.getText().equals("")){
        prodname.setText("Enter Product Name");
        prodname.setForeground(new Color(102,0,102));
        }
    }//GEN-LAST:event_prodnameFocusLost

    private void prodrateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_prodrateFocusGained
        // TODO add your handling code here:
         if(prodrate.getText().equals("Enter Product Price")){
        prodrate.setText("");
        prodrate.setForeground(new Color(102,0,102));
        }
    }//GEN-LAST:event_prodrateFocusGained

    private void prodrateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_prodrateFocusLost
        // TODO add your handling code here:
         if(prodrate.getText().equals("")){
        prodrate.setText("Enter Product Price");
        prodrate.setForeground(new Color(102,0,102));
        }
    }//GEN-LAST:event_prodrateFocusLost

    private void proddesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_proddesFocusGained
        // TODO add your handling code here:
         if(proddes.getText().equals("Enter Product Description")){
        proddes.setText("");
        proddes.setForeground(new Color(102,0,102));
        }
    }//GEN-LAST:event_proddesFocusGained

    private void proddesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_proddesFocusLost
        // TODO add your handling code here:
         if(proddes.getText().equals("")){
        proddes.setText("Enter Product Description");
        proddes.setForeground(new Color(102,0,102));
        }
    }//GEN-LAST:event_proddesFocusLost

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //close
        setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //refresh
        setVisible(false);
        new newProduct().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Product Save
        String pid=prodid.getText();
        String pname=prodname.getText();
        String prate=prodrate.getText();
        String pdesp=proddes.getText();
        String pactive=activebox.getSelectedItem().toString();
           try{
           Connection con=connection.getcon();
           Statement st=con.createStatement();
           int proadd=st.executeUpdate("insert into newproduct values('"+pid+"','"+pname+"','"+prate+"','"+pdesp+"','"+pactive+"')");
           if(proadd>0){
               JOptionPane.showMessageDialog(this, "Product Entry Sucessfully!!");
               setVisible(false);
               new newProduct().setVisible(true);
           }
            else{
           JOptionPane.showMessageDialog(this,"Data Entry Faild!!");
           }
           }
          
           catch(Exception e){
               JOptionPane.showMessageDialog(null, e);
           }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        try{
        Connection con=connection.getcon();
        Statement st =con.createStatement();
        ResultSet rs=st.executeQuery("select max(ProductId) from newproduct");
        if(rs.next()){
            int autoid=rs.getInt(1);
            autoid=autoid+1;
            String str=String.valueOf(autoid);
            prodid.setText(str);
        }
        else{
        prodid.setText("1");
        }
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, e);}
    }//GEN-LAST:event_formComponentShown

    private void prodnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prodnameKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(prodname.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Product Name Is Empty","Please Submit Name",JOptionPane.WARNING_MESSAGE);
            }
            else{prodrate.requestFocus();}
        }
        else if(evt.getKeyCode()==KeyEvent.VK_DOWN){
            if(prodname.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Product Rate Is Empty","Please Submit Name",JOptionPane.WARNING_MESSAGE);
            }
            else{prodrate.requestFocus();}
        }
    }//GEN-LAST:event_prodnameKeyPressed

    private void prodidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prodidKeyReleased
        // TODO add your handling code here:
        if(prodid.getText().equals("")){
                   }
    }//GEN-LAST:event_prodidKeyReleased

    private void prodrateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prodrateKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(prodrate.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Product Rate Is Empty","Please Submit Rate",JOptionPane.WARNING_MESSAGE);
            }
             else{proddes.requestFocus();}
        }
        else if(evt.getKeyCode()==KeyEvent.VK_DOWN){
            if(prodrate.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Product Rate Is Empty","Please Submit Rate",JOptionPane.WARNING_MESSAGE);
            }
            else{proddes.requestFocus();}
        }
    }//GEN-LAST:event_prodrateKeyPressed

    private void proddesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_proddesKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(proddes.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Product Rate Is Desciption","Please Submit Desciption",JOptionPane.WARNING_MESSAGE);
            }
             else{activebox.requestFocus();}
        }
        else if(evt.getKeyCode()==KeyEvent.VK_DOWN){
            if(proddes.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Product Rate Is Desciption","Please Submit Desciption",JOptionPane.WARNING_MESSAGE);
            }
             else{activebox.requestFocus();}
        }
    }//GEN-LAST:event_proddesKeyPressed

    private void activeboxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_activeboxKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(activebox.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(this, "Product Active Is Empty","Please Submit Activation",JOptionPane.WARNING_MESSAGE);
            }
            else{prodname.requestFocus();}
        }
        else if(evt.getKeyCode()==KeyEvent.VK_DOWN){
            if(prodrate.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Product Active Is Empty","Please Submit Activation",JOptionPane.WARNING_MESSAGE);
            } 
            else{prodname.requestFocus();}
            
        }
    }//GEN-LAST:event_activeboxKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> activebox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField proddes;
    private javax.swing.JTextField prodid;
    private javax.swing.JTextField prodname;
    private javax.swing.JTextField prodrate;
    // End of variables declaration//GEN-END:variables
}
