/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BuyinghouseBill;
import java.awt.Color;
import java.sql.*;
import ConnectionProject.connection;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
public class updateProduct extends javax.swing.JFrame {

    /**
     * Creates new form updateProduct
     */
    public updateProduct() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        prodid = new javax.swing.JTextField();
        produname = new javax.swing.JTextField();
        produrate = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        produdes = new javax.swing.JTextField();
        activebox = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(380, 160));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Product ID :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 170, 39));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Update Product");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 420, -1));

        prodid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        prodid.setForeground(new java.awt.Color(102, 0, 102));
        prodid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                prodidKeyReleased(evt);
            }
        });
        getContentPane().add(prodid, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 210, 30));

        produname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        produname.setForeground(new java.awt.Color(102, 0, 102));
        produname.setText("Enter Product Name");
        produname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                produnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                produnameFocusLost(evt);
            }
        });
        produname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produnameActionPerformed(evt);
            }
        });
        produname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                produnameKeyPressed(evt);
            }
        });
        getContentPane().add(produname, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 210, 30));

        produrate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        produrate.setForeground(new java.awt.Color(102, 0, 102));
        produrate.setText("Enter Product Price");
        produrate.setPreferredSize(new java.awt.Dimension(184, 23));
        produrate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                produrateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                produrateFocusLost(evt);
            }
        });
        produrate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                produrateKeyPressed(evt);
            }
        });
        getContentPane().add(produrate, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 210, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Rate");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 141, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Product Name");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 141, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Desciptions");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 141, 29));

        produdes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        produdes.setForeground(new java.awt.Color(102, 0, 102));
        produdes.setText("Enter Product Description");
        produdes.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                produdesFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                produdesFocusLost(evt);
            }
        });
        produdes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                produdesKeyPressed(evt);
            }
        });
        getContentPane().add(produdes, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 210, 29));

        activebox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        activebox.setForeground(new java.awt.Color(102, 0, 102));
        activebox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select One", "Yes", "No" }));
        activebox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                activeboxKeyPressed(evt);
            }
        });
        getContentPane().add(activebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 210, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Activate");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 141, 28));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BuyinghouseBill/update.png"))); // NOI18N
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BuyinghouseBill/refresh.png"))); // NOI18N
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, -1, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BuyinghouseBill/cancel button.png"))); // NOI18N
        jButton3.setText("Close");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 430, -1, -1));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BuyinghouseBill/search.png"))); // NOI18N
        jButton4.setText("Search");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 170, 210, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BuyinghouseBill/updated.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 580, 10));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 580, 10));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BuyinghouseBill/pexels-mentatdgt-1167160.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void prodidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prodidKeyReleased
        // TODO add your handling code here:
        if(prodid.getText().equals("")){
        }
    }//GEN-LAST:event_prodidKeyReleased

    private void produnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_produnameFocusGained
        //name focus
        if(produname.getText().equals("Enter Product Name")){
            produname.setText("");
            produname.setForeground(new Color(102,0,102));
        }
    }//GEN-LAST:event_produnameFocusGained

    private void produnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_produnameFocusLost
        // TODO add your handling code here:
        if(produname.getText().equals("")){
            produname.setText("Enter Product Name");
            produname.setForeground(new Color(102,0,102));
        }
    }//GEN-LAST:event_produnameFocusLost

    private void produnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_produnameActionPerformed

    private void produnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_produnameKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(produname.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Product Name Is Empty","Please Submit Name",JOptionPane.WARNING_MESSAGE);
            }
            else{produrate.requestFocus();}
        }
        else if(evt.getKeyCode()==KeyEvent.VK_DOWN){
            if(produname.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Product Rate Is Empty","Please Submit Name",JOptionPane.WARNING_MESSAGE);
            }
            else{produrate.requestFocus();}
        }
    }//GEN-LAST:event_produnameKeyPressed

    private void produrateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_produrateFocusGained
        // TODO add your handling code here:
        if(produrate.getText().equals("Enter Product Price")){
            produrate.setText("");
            produrate.setForeground(new Color(102,0,102));
        }
    }//GEN-LAST:event_produrateFocusGained

    private void produrateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_produrateFocusLost
        // TODO add your handling code here:
        if(produrate.getText().equals("")){
            produrate.setText("Enter Product Price");
            produrate.setForeground(new Color(102,0,102));
        }
    }//GEN-LAST:event_produrateFocusLost

    private void produrateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_produrateKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(produrate.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Product Rate Is Empty","Please Submit Rate",JOptionPane.WARNING_MESSAGE);
            }
            else{produdes.requestFocus();}
        }
        else if(evt.getKeyCode()==KeyEvent.VK_DOWN){
            if(produrate.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Product Rate Is Empty","Please Submit Rate",JOptionPane.WARNING_MESSAGE);
            }
            else{produdes.requestFocus();}
        }
    }//GEN-LAST:event_produrateKeyPressed

    private void produdesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_produdesFocusGained
        // TODO add your handling code here:
        if(produdes.getText().equals("Enter Product Description")){
            produdes.setText("");
            produdes.setForeground(new Color(102,0,102));
        }
    }//GEN-LAST:event_produdesFocusGained

    private void produdesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_produdesFocusLost
        // TODO add your handling code here:
        if(produdes.getText().equals("")){
            produdes.setText("Enter Product Description");
            produdes.setForeground(new Color(102,0,102));
        }
    }//GEN-LAST:event_produdesFocusLost

    private void produdesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_produdesKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(produdes.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Product Rate Is Desciption","Please Submit Desciption",JOptionPane.WARNING_MESSAGE);
            }
            else{activebox.requestFocus();}
        }
        else if(evt.getKeyCode()==KeyEvent.VK_DOWN){
            if(produdes.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Product Rate Is Desciption","Please Submit Desciption",JOptionPane.WARNING_MESSAGE);
            }
            else{activebox.requestFocus();}
        }
    }//GEN-LAST:event_produdesKeyPressed

    private void activeboxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_activeboxKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(activebox.getSelectedIndex()==0){
                JOptionPane.showMessageDialog(this, "Product Active Is Empty","Please Submit Activation",JOptionPane.WARNING_MESSAGE);
            }
            else{produname.requestFocus();}
        }
        else if(evt.getKeyCode()==KeyEvent.VK_DOWN){
            if(produrate.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Product Active Is Empty","Please Submit Activation",JOptionPane.WARNING_MESSAGE);
            }
            else{produname.requestFocus();}

        }
    }//GEN-LAST:event_activeboxKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Product Update
        String pid=prodid.getText();
        String pname=produname.getText();
        String prate=produrate.getText();
        String pdesp=produdes.getText();
        String pactive=activebox.getSelectedItem().toString();
        try{
            Connection con=connection.getcon();
            Statement st=con.createStatement();
            int proup=st.executeUpdate("update newproduct set `ProductName`='"+pname+"',`ProductPrice`='"+prate+"',`ProductDescription`='"+pdesp+"',`ProductActive`='"+pactive+"' where `ProductId`='"+pid+"'");
            if(proup>0){
                JOptionPane.showMessageDialog(this, "Product Update Sucessfully!!");
                setVisible(false);
                new updateProduct().setVisible(true);
            }
            else{
                JOptionPane.showMessageDialog(this,"Data Entry Faild!!");
            }
        }

        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //refresh
        setVisible(false);
        new updateProduct().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //close
        setVisible(false);

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String upsearch=prodid.getText();
        try{
        Connection con=connection.getcon();
        Statement st=con.createStatement();
        ResultSet rs=st.executeQuery("select *from newproduct where `ProductId`='"+upsearch+"'");
        if(rs.next()){
        produname.setText(rs.getString(2));
        produrate.setText(rs.getString(3));
        produdes.setText(rs.getString(4));
        activebox.setSelectedItem(rs.getString(5));
        }
        else{
        JOptionPane.showMessageDialog(this,"Not Found Product");}
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null,e);}
        
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updateProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updateProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updateProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updateProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updateProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> activebox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField prodid;
    private javax.swing.JTextField produdes;
    private javax.swing.JTextField produname;
    private javax.swing.JTextField produrate;
    // End of variables declaration//GEN-END:variables
}
