/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BuyinghouseBill;

import java.awt.Color;
import java.sql.*;
import ConnectionProject.connection;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author akib2
 */
public class updateBuyer extends javax.swing.JFrame {

    /**
     * Creates new form updateBuyer
     */
    public updateBuyer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ubc = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        ube = new javax.swing.JTextField();
        ubadd = new javax.swing.JTextField();
        ubn = new javax.swing.JTextField();
        ubgen = new javax.swing.JComboBox<>();
        searchtf = new javax.swing.JTextField();
        searchbutton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(380, 160));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BuyinghouseBill/save.png"))); // NOI18N
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 51, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BuyinghouseBill/Knob-Refresh-icon.png"))); // NOI18N
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 440, -1, 30));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 102, 204));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BuyinghouseBill/close Jframe.png"))); // NOI18N
        jButton3.setText("Close");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(416, 440, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Update Buyer");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 361, 70));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BuyinghouseBill/Update buyer.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 24, 73, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 204));
        jLabel3.setText("Update Name :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 210, 32));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 255, 204));
        jLabel4.setText("Update Contract :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 210, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 255, 204));
        jLabel5.setText("Update Buyer Email :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 210, 34));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 255, 204));
        jLabel6.setText("Update Buyer Address :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, 26));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 255, 204));
        jLabel7.setText("Update Gender :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 210, 31));

        ubc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ubc.setForeground(new java.awt.Color(102, 102, 102));
        ubc.setText("For Update Contract");
        ubc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ubcFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ubcFocusLost(evt);
            }
        });
        ubc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ubcKeyPressed(evt);
            }
        });
        getContentPane().add(ubc, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 213, 220, 32));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 90, 544, -1));

        ube.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ube.setForeground(new java.awt.Color(102, 102, 102));
        ube.setText("For Update Email");
        ube.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ubeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ubeFocusLost(evt);
            }
        });
        ube.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ubeKeyPressed(evt);
            }
        });
        getContentPane().add(ube, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 264, 220, 32));

        ubadd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ubadd.setForeground(new java.awt.Color(102, 102, 102));
        ubadd.setText("For Update Address");
        ubadd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ubaddFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ubaddFocusLost(evt);
            }
        });
        ubadd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ubaddKeyPressed(evt);
            }
        });
        getContentPane().add(ubadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 309, 220, 32));

        ubn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ubn.setForeground(new java.awt.Color(102, 102, 102));
        ubn.setText("For Update Name");
        ubn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ubnFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ubnFocusLost(evt);
            }
        });
        ubn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ubnKeyPressed(evt);
            }
        });
        getContentPane().add(ubn, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 163, 220, 32));

        ubgen.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ubgen.setForeground(new java.awt.Color(102, 102, 102));
        ubgen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select One", "Male", "Female", "others" }));
        getContentPane().add(ubgen, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 362, 220, 30));

        searchtf.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        searchtf.setForeground(new java.awt.Color(0, 102, 51));
        searchtf.setText("Search Buyer Info");
        searchtf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchtfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchtfFocusLost(evt);
            }
        });
        searchtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchtfActionPerformed(evt);
            }
        });
        getContentPane().add(searchtf, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 100, 230, -1));

        searchbutton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        searchbutton.setForeground(new java.awt.Color(0, 0, 102));
        searchbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BuyinghouseBill/search.png"))); // NOI18N
        searchbutton.setText("Search");
        searchbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(searchbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 151, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BuyinghouseBill/ccaa9c607a1fef34994c36501e6178a2.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Update Buyer
        String uname=ubn.getText();
        String contractch=searchtf.getText();
        String ucontract=ubc.getText();
        String uemail=ube.getText();
        String uadd=ubadd.getText();
        String ugen=ubgen.getSelectedItem().toString();
        try{
        Connection con=connection.getcon();
        Statement st=con.createStatement();
        int upb=st.executeUpdate("update `newbuyer` set `BuyerName` ='"+uname+"',`BuyerPhone`='"+ucontract+"',`BuyerEmail`='"+uemail+"',`BuyerAddress`='"+uadd+"',`Gender`='"+ugen+"' where `BuyerPhone`='"+ucontract+"'");
        if(upb>0){
            JOptionPane.showMessageDialog(this, "Buyer Details Updated Sucesessfully!!!");
            setVisible(false);
            new updateBuyer().setVisible(true);
        }
        else{
        JOptionPane.showMessageDialog(this, "Buyer data Not Update");}
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
    }        
            
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
      
       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
       new updateBuyer().setVisible(true);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ubnFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ubnFocusGained
        // TODO add your handling code here:
        if(ubn.getText().equals("For Update Name")){
        ubn.setText("");
        ubn.setForeground(new Color(102,102,102));}
    }//GEN-LAST:event_ubnFocusGained

    private void ubcFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ubcFocusLost
        // TODO add your handling code here:
          if(ubc.getText().equals("")){
        ubc.setText("For Update Contract");
        ubc.setForeground(new Color(102,102,102));}
    }//GEN-LAST:event_ubcFocusLost

    private void ubeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ubeFocusGained
        // TODO add your handling code here:
         if(ube.getText().equals("For Update Email")){
        ube.setText("");
        ube.setForeground(new Color(102,102,102));
    }    
    }//GEN-LAST:event_ubeFocusGained

    private void ubcFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ubcFocusGained
        // TODO add your handling code here:
         if(ubc.getText().equals("For Update Contract")){
        ubc.setText("");
        ubc.setForeground(new Color(102,102,102));
    }  
    }//GEN-LAST:event_ubcFocusGained

    private void ubeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ubeFocusLost
        // TODO add your handling code here:
          if(ube.getText().equals("")){
        ube.setText("For Update Email");
        ube.setForeground(new Color(102,102,102));}
    }//GEN-LAST:event_ubeFocusLost

    private void ubaddFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ubaddFocusGained
        // TODO add your handling code here:
         if(ubadd.getText().equals("For Update Address")){
        ubadd.setText("");
        ubadd.setForeground(new Color(102,102,102));
    }  
    }//GEN-LAST:event_ubaddFocusGained

    private void ubaddFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ubaddFocusLost
        // TODO add your handling code here:
          if(ubadd.getText().equals("")){
        ubadd.setText("For Update Address");
        ubadd.setForeground(new Color(102,102,102));}
    }//GEN-LAST:event_ubaddFocusLost

    private void ubnFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ubnFocusLost
        // TODO add your handling code here:
        if(ubn.getText().equals("")){
        ubn.setText("For Update Name");
        ubn.setForeground(new Color(102,102,102));}
    }//GEN-LAST:event_ubnFocusLost

    private void searchbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbuttonActionPerformed
        //Search
        String search=searchtf.getText();
        try{
        Connection con=connection.getcon();
        Statement st=con.createStatement();
        ResultSet rs=st.executeQuery("select *from newbuyer where BuyerPhone like'"+search+"%'");
        if(rs.next()){
        ubn.setText(rs.getString(1));
        ubc.setText(rs.getString(2));
        ube.setText(rs.getString(3));
        ubadd.setText(rs.getString(4));
        ubgen.setSelectedItem(rs.getString(5));}
        else{
           
        JOptionPane.showMessageDialog(this, "Not Found Here Buyer");}
        
       }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Buyer Is Not Found Here","Please Give Right Contract",JOptionPane.WARNING_MESSAGE);}
        
    }//GEN-LAST:event_searchbuttonActionPerformed

    private void searchtfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchtfFocusGained
        // focus gain Search Textfield
       if(searchtf.getText().equals("Search Buyer Info")){
       searchtf.setText("");
       searchtf.setForeground(new Color(0,102,51));}
    }//GEN-LAST:event_searchtfFocusGained

    private void searchtfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchtfFocusLost
        //focus lost Search Textfield
        if(searchtf.getText().equals("Search Buyer Info")){
       searchtf.setText("");
       searchtf.setForeground(new Color(0,102,51));}
    }//GEN-LAST:event_searchtfFocusLost

    private void ubnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ubnKeyPressed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_ubnKeyPressed

    private void ubcKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ubcKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ubcKeyPressed

    private void ubeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ubeKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ubeKeyPressed

    private void ubaddKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ubaddKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ubaddKeyPressed

    private void searchtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchtfActionPerformed
        // TODO add your handling code here:
  
    }//GEN-LAST:event_searchtfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updateBuyer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updateBuyer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updateBuyer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updateBuyer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updateBuyer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton searchbutton;
    private javax.swing.JTextField searchtf;
    private javax.swing.JTextField ubadd;
    private javax.swing.JTextField ubc;
    private javax.swing.JTextField ube;
    private javax.swing.JComboBox<String> ubgen;
    private javax.swing.JTextField ubn;
    // End of variables declaration//GEN-END:variables
}
